language: julia
sudo: false
addons:
  apt:
    packages:
      - texlive
os:
  - linux
  - osx
julia:
  - release
  - 0.4
notifications:
  - email: false
#script:
  - julia -e 'Pkg.clone(pwd()); Pkg.test("Nemo")'
